name: Reusable - Pull Request
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
      open:
        required: true
        type: boolean
        default: true
      labels:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      docker-login:
        required: true
      docker-password:
        required: true
      github-private-actions-pat:
        required: true

permissions:
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Preview deployments controller
        uses: ./.github/actions/preview_controller
        id: controller
        with:
          labels: ${{ inputs.labels }}
          open: ${{ inputs.open }}
          env-label: |
            preview: deploy

    outputs:
      namespace: ${{ inputs.ref }}
      labels_env: ${{ steps.controller.outputs.labels_env }}
      deploy_envs: ${{ steps.controller.outputs.deploy_envs }}
      destroy_envs: ${{ steps.controller.outputs.destroy_envs }}

  build:
    runs-on: ["self-hosted"]
    if: ${{ inputs.open }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}
          login: ${{ secrets.docker-login }}
          password: ${{ secrets.docker-password }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  test:
    runs-on: ["self-hosted"]
    if: ${{ inputs.open }}
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Tests
        id: test
        uses: ./.github/actions/docker-compose-tests-run
        with:
          file: codefresh/test/docker-compose.yml
          service: app
          command: codefresh/test/test.sh

  deploy:
    runs-on: ["self-hosted"]
    if: ${{ needs.context.outputs.deploy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.deploy_envs) }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ context, build, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Environment Info
        uses: ./.github/actions/environments
        id: environment
        with:
          environment: ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}

      - name: Deploy
        uses: ./.github/actions/deploy
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.build.outputs.image }}
          image-tag: ${{ needs.build.outputs.tag }}
          operation: deploy
          debug: false
        env:
          ISTIO_INSTALLED: false
          COLOR: green
          RELEASE_NAME: example-app-green

  destroy:
    runs-on: ["self-hosted"]
    if: ${{ needs.context.outputs.destroy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.destroy_envs) }}
    permissions:
      pull-requests: write
      deployments: write
    needs: [ context ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Seek deployment
        uses: ./.github/actions/get_deployment
        id: deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          env-name: ${{ matrix.env }}
          ref-to-search: ${{ inputs.ref }}
          status: success

      - name: Environment Info
        uses: ./.github/actions/environments
        if: ${{ steps.deployment.outputs.deploymentId != '' }}
        id: environment
        with:
          environment: ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}

      - name: Destroy
        uses: ./.github/actions/deploy
        if: ${{ steps.deployment.outputs.deploymentId != '' }}
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: "<none>"
          image-tag: "<none>"
          operation: destroy
          debug: false
        env:
          ISTIO_INSTALLED: false
          COLOR: green
          RELEASE_NAME: example-app-green

      - name: Cleanup label
        uses: ./.github/actions/preview_controller_label_cleanup
        if: ${{ ! inputs.open }}
        with:
          labels_env: ${{ needs.context.outputs.labels_env }}
          env: ${{ matrix.env }}

      - name: Inactivate deployment
        uses: chrnorm/deployment-status@v2.0.0
        if: ${{ steps.deployment.outputs.deploymentId != '' }}
        with:
          state: inactive
          token: ${{ github.token }}
          deployment-id: ${{ steps.deployment.outputs.deploymentId }}
