name: Dockerized Appication ( ECR/Spacelift ) - Main branch
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      registry:
        description: "Docker registry"
        required: true
      github-private-actions-pat:
        required: true
      ecr-region:
        required: true
        description: "AWS region for ECR"
      ecr-iam-role:
        required: true
        description: "IAM for ECR"
      spacelift-organization:
        description: "Spacelift organization"
        required: true
      spacelift-api-key-id:
        required: true
      spacelift-api-key-secret:
        required: true

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-dockerized-app-build.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
    secrets:
      ecr-region: ${{ secrets.ecr-region }}
      ecr-iam-role: ${{ secrets.ecr-iam-role }}
      registry: ${{ secrets.registry }}
      secret-outputs-passphrase: ${{ secrets.secret-outputs-passphrase }}

  cd:
    uses: vstreaminc/github-action-workflows/.github/workflows/cd-ecs.yml@main
    needs: [ ci ]
    with:
      image: ${{ needs.ci.outputs.image }}
      tag: ${{ needs.ci.outputs.tag }}
      repository: ${{ inputs.repository }}
      spacelift-organization: ${{ inputs.spacelift-organization }}
      environment: dev
    secrets:
      secret-outputs-passphrase: "${{ secrets.secret-outputs-passphrase }}"
      github-private-actions-pat: "${{ secrets.github-private-actions-pat }}"
      spacelift-api-key-id: "${{ secrets.spacelift-api-key-id }}"
      spacelift-api-key-secret: "${{ secrets.spacelift-api-key-secret }}"

  release:
    uses:  cloudposse/github-actions-workflows/.github/workflows/controller-draft-release.yml@main
    needs: [ cd ]
    secrets:
      github-private-actions-pat: ${{ secrets.github-private-actions-pat }}
